name: Apply Patch from Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # Only act if the comment contains '/apply' and the commenter is allowed
    if: |
      contains(github.event.comment.body, '/apply') &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.actor == 'HomoYouDidnt'
      )
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract patch from comment
        id: extract
        shell: bash
        env:
          BODY: ${{ github.event.comment.body }}
        run: |
          printf "%s" "$BODY" > /tmp/comment.txt
          awk 'BEGIN{inb=0}
               /^```(diff|patch)/{inb=1; next}
               /^```/{ if(inb){inb=0; exit} }
               { if(inb) print }' /tmp/comment.txt > /tmp/patch.diff
          if [ ! -s /tmp/patch.diff ]; then
            echo "No ```diff or ```patch fenced block found in the comment."
            exit 1
          fi
          echo "patch=/tmp/patch.diff" >> "$GITHUB_OUTPUT"

      - name: Create branch from dev and apply patch
        shell: bash
        env:
          PATCH: ${{ steps.extract.outputs.patch }}
        run: |
          git config user.name "kloros-bot"
          git config user.email "bot@users.noreply.github.com"

          git fetch origin dev
          git switch -c "bot/patch-$(date +%Y%m%d-%H%M%S)" origin/dev

          if ! git apply --whitespace=fix -3 "$PATCH"; then
            echo "Patch failed to apply cleanly."
            git checkout -- .
            exit 1
          fi

          git add -A
          git commit -m "apply: patch from @${GITHUB_ACTOR}"
          git push -u origin HEAD

      - name: Open PR into dev
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          title: "Apply patch from @${{ github.actor }}"
          body: |
            Automated PR created from a comment by @${{ github.actor }} on #${{ github.event.issue.number }}.

            Original comment: ${{ github.event.comment.html_url }}
          labels: |
            bot
            patch
