name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U black ruff mypy pytest pre-commit
          pip install -e .

      - name: Run Black
        run: black --check .

      - name: Run Ruff
        run: ruff check .

      - name: Run MyPy
        run: mypy src

      - name: Run pytest
        run: pytest -q
