name: Open PR from bot branches

on:
  push:
    branches:
      - "bot/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Open or update PR into dev
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const owner = context.payload.repository.owner.login;
            const repo  = context.payload.repository.name;
            const head  = context.ref.replace("refs/heads/",""); // e.g. bot/astraea
            const base  = "dev";
            const title = `Bot: ${head}`;
            const body  = `Automated PR from **${head}**`;
            const prs = await github.rest.pulls.list({ owner, repo, state: "open", head: `${owner}:${head}`, base });
            if (prs.data.length) { core.info(`PR already open: #${prs.data[0].number}`); return; }
            const { data: pr } = await github.rest.pulls.create({ owner, repo, head, base, title, body });
            core.info(`Opened PR #${pr.number} from ${head} to ${base}`);
